// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ProjetoTesteCad.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Realizar a interação das telas")]
    [NUnit.Framework.CategoryAttribute("interacaoTelas")]
    public partial class RealizarAInteracaoDasTelasFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "InteracaoTelas.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Realizar a interação das telas", "\tComo usuário do sistema\r\n\tEu quero poder interagir com as telas do site instituc" +
                    "ional e funcional.", ProgrammingLanguage.CSharp, new string[] {
                        "interacaoTelas"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Realizar a interacao do cliente no site institucional")]
        [NUnit.Framework.CategoryAttribute("InteragirTelasInstitucional")]
        [NUnit.Framework.TestCaseAttribute("id_serv_index", null)]
        [NUnit.Framework.TestCaseAttribute("id_produto_index", null)]
        [NUnit.Framework.TestCaseAttribute("id_simula_index", null)]
        [NUnit.Framework.TestCaseAttribute("id_equipe_index", null)]
        [NUnit.Framework.TestCaseAttribute("id_contato_index", null)]
        public virtual void RealizarAInteracaoDoClienteNoSiteInstitucional(string opcao, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InteragirTelasInstitucional"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Realizar a interacao do cliente no site institucional", null, @__tags);
#line 8
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 9
  testRunner.Given("que estou na página inicial do site institucional", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
  testRunner.When(string.Format("clico em {0}", opcao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
  testRunner.Then(string.Format("a tela deve ir até a parte da {0}", opcao), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Realizar a interação do cliente do cadastro ate o login")]
        [NUnit.Framework.CategoryAttribute("InteragirTelasAteLogin")]
        public virtual void RealizarAInteracaoDoClienteDoCadastroAteOLogin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Realizar a interação do cliente do cadastro ate o login", null, new string[] {
                        "InteragirTelasAteLogin"});
#line 21
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 22
   testRunner.Given("que estou na página inicial do site institucional", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
   testRunner.When("Acesso a pagina de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
   testRunner.And("sou direcionado para a página de cadastro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
   testRunner.When("clico que ja possuo uma conta", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
   testRunner.And("sou redirecionado para a página de login", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
   testRunner.Then("Faço o login com um usuário existente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
   testRunner.And("sou direcionado para a dashboard", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Realizar a interação do cliente no site funcional")]
        [NUnit.Framework.CategoryAttribute("InteragirTelasFuncional")]
        [NUnit.Framework.TestCaseAttribute("id_silos", null)]
        [NUnit.Framework.TestCaseAttribute("id_vendas", null)]
        [NUnit.Framework.TestCaseAttribute("id_qualidade", null)]
        public virtual void RealizarAInteracaoDoClienteNoSiteFuncional(string pagina, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "InteragirTelasFuncional"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Realizar a interação do cliente no site funcional", null, @__tags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 32
   testRunner.Given("que efetuei o login no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
   testRunner.And(string.Format("clico em {0}", pagina), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
   testRunner.Then(string.Format("devo ser direcionado para página {0}", pagina), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 35
  testRunner.And("saio do sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
